export const Colors = {
  light: {
    text: '#000000',
    background: '#FFFFFF',
    tint: '#4A90E2',
    tabIconDefault: '#CCCCCC',
    tabIconSelected: '#4A90E2',
    tabBackground: '#FFFFFF',
    errorText: '#D32F2F',
    buttonBackground: '#4A90E2',
    buttonText: '#FFFFFF',
    border: '#E0E0E0',
  },
  dark: {
    text: '#FFFFFF',
    background: '#1A1A1A',
    tint: '#4A90E2',
    tabIconDefault: '#666666',
    tabIconSelected: '#4A90E2',
    tabBackground: '#1A1A1A',
    errorText: '#FF6B6B',
    buttonBackground: '#4A90E2',
    buttonText: '#FFFFFF',
    border: '#333333',
  },
}; 